"""initial

Revision ID: 3a0306aaec30
Revises: 
Create Date: 2026-01-28 13:10:57.318636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0306aaec30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_drivers_is_active'), 'drivers', ['is_active'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partner_type', sa.Enum('CUSTOMER', 'VENDOR', 'PARTNER', name='partner_type_enum'), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_partners_is_active'), 'partners', ['is_active'], unique=False)
    op.create_index(op.f('ix_partners_partner_type'), 'partners', ['partner_type'], unique=False)
    op.create_table('purchase_places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_purchase_places_is_active'), 'purchase_places', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('current_driver_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_is_active'), 'vehicles', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_start_date', sa.String(), nullable=False),
    sa.Column('estimated_end_date', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('purchase_place_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.Column('starting_km', sa.Float(), nullable=True),
    sa.Column('ending_km', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('tonnage', sa.Float(), nullable=True),
    sa.Column('rate_per_ton', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('expenses', sa.JSON(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('amount_given_to_driver', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['purchase_place_id'], ['purchase_places.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_is_active'), 'trips', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_is_active'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_active'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_purchase_places_is_active'), table_name='purchase_places')
    op.drop_table('purchase_places')
    op.drop_index(op.f('ix_partners_partner_type'), table_name='partners')
    op.drop_index(op.f('ix_partners_is_active'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_drivers_is_active'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
