"""nullable_driver_license

Revision ID: b99b479acf72
Revises: 1d773eff200b
Create Date: 2026-02-02 16:23:11.113532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99b479acf72'
down_revision: Union[str, Sequence[str], None] = '1d773eff200b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
